### ISSUE TITLE
CLI issue - 'module' key not found

### ISSUE THREAD

**Issue by seb-acsc** [CybercentreCanada/Maco#66]
The CLI tries to access the list of extractor instances found by the maco collector, and access the 'module' property, which was previously an instance of a maco extractor.

Due to the new importing behaviour, this property no longer exists and the CLI crashes.

The CLI is attempting to print metadata for the maco extractor such as family, author, etc. This is also useful when interacting with maco programmatically.

I've attempted to import via importlib manually as a fix but due to the modifications that are made by uv, these imports are no longer valid to import directly.

I've added a test in my own branch that shows this issue - https://github.com/seb-acsc/Maco/blob/feat/library_check/tests/test_cli.py.

```python

path_extractors = '/home/seb/work/Maco/demo_extractors', path_samples = '/home/seb/work/Maco/tests/data', include = [], exclude = []

    def process_filesystem(
        path_extractors: str,
        path_samples: str,
        include: List[str],
        exclude: List[str],
        *,
        pretty: bool,
        force: bool,
        include_base64: bool,
        create_venv: bool = False,
    ):
        if force:
            logger.warning("force execute will cause errors if an extractor requires a yara rule hit during execution")
        collected = collector.Collector(path_extractors, include=include, exclude=exclude, create_venv=create_venv)
    
        logger.info(f"extractors loaded: {[x for x in collected.extractors.keys()]}\n")
        for _, extractor in collected.extractors.items():
>           extractor = extractor["module"]
E           KeyError: 'module'

maco/cli.py:101: KeyError
==================================================================================================================================== short test summary info =====================================================================================================================================
FAILED tests/test_cli.py::TestCLI::test_process_filesystem - KeyError: 'module'
1 failed in 0.69s
```

**Comment by cccs-rs** [comment]
Should be resolved in this release: https://github.com/CybercentreCanada/Maco/releases/tag/v1.2.2
