### ISSUE TITLE
Family as list

### ISSUE THREAD

**Issue by thatseb** [CybercentreCanada/Maco#8]
We have a couple decoders that identify malware with several names, like an internal name and another name gathered from other reporting. We would like to store both of these names on the model/extractor.

Would these changes fit your usage of the model as well? I'll draw up a PR if so.

```
class Extractor:
    family: Union[str, List[str]] = None  # family of malware that is detected by the extractor
```

```
class ExtractorModel(ForbidModel):
    family: Union[str, List[str]] # family of malware that was detected
```

**Comment by cccs-kevin** [comment]
Associated `assemblyline-base` PR: https://github.com/CybercentreCanada/assemblyline-base/pull/978
